# 头部菜单，title: link
menu:
  首页: /
  分类: /categories
  标签: /tags
  归档: /archives
  关于: /about

# 是否显示目录
TOC: false

# 是否自动播放音乐
autoplay: false

# 默认音乐（随机播放）
mp3:
    - https://m8.music.126.net/20200915215716/edd9a6d57f4a085b4a5c6b4a8fc6d86c/ymusic/0658/560f/045e/129d595750aeb786d78e346ead18b8b7.mp3
    - https://m8.music.126.net/20200915220006/b137ae7922b7385d8bd302a21b1cdb6d/ymusic/555f/0759/0158/b574fbcc2c0315efe4f162caf545d135.mp3
    - https://m7.music.126.net/20200915220048/944af04607fd9a1c3d52e123fd00c089/ymusic/8393/15da/ae04/5739618ddf372bb5e0636a4a46de01ae.mp3
    - https://m7.music.126.net/20200915220113/16b89a8e3f37cf9944524e7259441b77/ymusic/045c/5658/5158/3677fc4c4ea27c511a5af2caa001bd76.mp3
    - https://m7.music.126.net/20200915220132/9f067394c65a359f89d43a5b2fa44577/ymusic/010b/0758/0508/6ad7331c4802995fb4152b42b5bc73b3.mp3
    - https://m8.music.126.net/20200915220146/f2901d384260c50f89eed73b5360877e/ymusic/040b/075c/0e5d/3ae7d9296606e46cdd96975caf5b35c0.mp3
    - https://m7.music.126.net/20200915220223/19534cb2640aed69d00037a765b0abee/ymusic/1f6b/65c0/cb21/62eb51be45f1d7d44bc22add4a2287a8.mp3

# 首页封面图, 为空时取文章的cover作为封面(注意跨域问题,建议使用同源图片)
welcome_cover:
  - img/welcome-sea.jpg


# 默认文章封面图（随机调用,支持外链）
cover:
  - /img/welcome-blue.jpg
  - /img/welcome-darkcyan.jpg
  - /img/welcome-double.jpg
  - /img/welcome-purple.jpg
  - /img/welcome-red.jpg
  - /img/welcome-sky.jpg
  - /img/mhsj.jpg


# 是否使用mathjax
mathjax: false


# 是否关闭默认滚动条
scrollbar: true

# 本地搜索,请将索引文件放在网站根目录,或修改主题js文件的path值
local_search:
    # 是否启用
    enable: false

# 是否显示 一言(hitokoto)
hitokoto: true

# 链接(可选:facebook,twitter,github,wechat,email)
links:
    facebook: /
    twitter: /
    github: /
    wechat: /
    email: mailto:xxxx@gmail.com

# 备案
beian:
    # 是否显示备案信息
    enable: true
    # 是否在主页面最底下显示备案信息(虽然丑，但是完全满足规定要求)
    enableFooter: false
    # 备案号
    beianInfo: 冀ICP备xxxxxxx号
    # 链接地址
    link: http://www.beian.miit.gov.cn

# Gitalk 评论插件（https://github.com/gitalk/gitalk）
gitalk:
    # 是否启用评论功能
    enable: false
    # 是否自动展开评论框
    autoExpand: false
    # 应用编号
    clientID: ''
    # 应用秘钥
    clientSecret: ''
    # issue仓库名
    repo: ''
    # Github名
    owner: ''
    # Github名
    admin: ['']
    # Ensure uniqueness and length less than 50
    id: location.pathname
    # Facebook-like distraction free mode
    distractionFreeMode: false

# 网站关键字
keywords: Fechin

# 要使用google_analytics进行统计的话，这里需要配置ID
google_analytics:

# 网站ico
favicon: /img/favicon.png

# rss文件
rss: atom.xml
